[package]
name = "markdown-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pulldown-cmark = "0.13"  # or comrak = "0.12"
wasm-bindgen = "0.2"    # For interfacing with JavaScript